import type { Metadata } from "next";
import "./globals.css";
import { indieFlower } from "@/app/ui/fonts";
import SideNav from "@/app/ui/home/sidenav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className={`${indieFlower.className} min-h-full`}>
        <div className="min-h-screen flex">
          <SideNav />
          <main className="flex-1">{children}</main>
        </div>
      </body>
    </html>
  );
}
