import type { Metadata } from "next";
import "./globals.css";
import { indieFlower } from "@/app/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className={`${indieFlower.className} min-h-full flex flex-col`}>
        {children}
      </body>
    </html>
  );
}
